import { btn } from "./interface";
const buttons : btn[]=[
{
         id:"7",
         type:"numberbutton",
         value:"7",
},
{
         id:"8",
         type:"numberbutton",
         value:"8"
},
{
         id:"9",
         type:"numberbutton",
         value:"9"
},
{
         id:"del",
         type:"deletebutton",
         value:"DEL"
},
{
         id:"4",
         type:"numberbutton",
         value:"4"
},{
         id:"5",
         type:"numberbutton",
         value:"5"
},{
         id:"6",
         type:"numberbutton",
         value:"6"
},{
         id:"add",
         type:"numberbutton",
         value:"+"
},{
         id:"1",
         type:"numberbutton",
         value:"1"
},{
         id:"2",
         type:"numberbutton",
         value:"2"
},{
         id:"3",
         type:"numberbutton",
         value:"3"
},{
         id:"minus",
         type:"numberbutton",
         value:"."
},{
         id:"float",
         type:"numberbutton",
         value:"."
},{
         id:"0",
         type:"numberbutton",
         value:"0"
},{
         id:"divide",
         type:"numberbutton",
         value:"/"
},{
         id:"multiply",
         type:"numberbutton",
         value:"*"
},{
         id:"reset",
         type:"resetbutton",
         value:"RESET"
},{
         id:"answer",
         type:"answerbutton",
         value:"="
},
]
export default buttons;